# GoReleaser configuration for Foundry
# See: https://goreleaser.com for full documentation

version: 2

before:
  hooks:
    # Run all checks before building
    - make check

builds:
  - id: foundry
    binary: foundry
    main: ./cmd/foundry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      # Inject version info at build time
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: foundry-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - DESIGN.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^typo"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

dockers_v2:
  - id: foundry
    dockerfile: Dockerfile
    images:
      - "ghcr.io/jbweber/foundry"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "A Go-based CLI tool for managing libvirt VMs"
      "org.opencontainers.image.url": "https://github.com/jbweber/foundry"
      "org.opencontainers.image.source": "https://github.com/jbweber/foundry"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"

release:
  github:
    owner: jbweber
    name: foundry
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Foundry {{ .Version }}

    A Go-based CLI tool for managing libvirt VMs with simple YAML configuration.
  footer: |
    ## Installation

    ### Binary
    Download the appropriate binary for your platform from the assets below.

    ```bash
    tar -xzf foundry_{{ .Version }}_linux_amd64.tar.gz
    sudo mv foundry /usr/local/bin/
    ```

    ### Docker
    ```bash
    docker pull ghcr.io/jbweber/foundry:{{ .Version }}
    ```

    ## What's Next?
    Check out the [documentation](https://github.com/jbweber/foundry/blob/main/README.md) for usage examples.
